In [1]:
pip install yfinance pandas numpy plotly

Requirement already satisfied: yfinance in c:\users\ynikh\anaconda3\lib\site-packages (0.2.55)
Requirement already satisfied: pandas in c:\users\ynikh\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\ynikh\anaconda3\lib\site-packages (1.24.3)
Requirement already satisfied: plotly in c:\users\ynikh\anaconda3\lib\site-packages (5.9.0)
Requirement already satisfied: requests>=2.31 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\ynikh\anaconda3\lib\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ynikh\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\ynikh\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\ynikh\anaconda3\lib\site-packages (from plotly) (8.2.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\ynikh\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.5 in c:\users\ynikh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ynikh\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ynikh\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ynikh\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ynikh\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2023.7.22)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import pandas_datareader as pdr
import yfinance as yf

In [10]:
tickers = ['AAPL','TSLA','JPM','XOM','UNH','HD','NKE']
bd = '2019-1-1'
ed = '2025-12-31'
stock_data = yf.download(tickers,bd,ed)
# stock_data = stock_data['Adj Close']
stock_data = stock_data['Close']
stock_data

[*********************100%***********************]  7 of 7 completed

Ticker,AAPL,HD,JPM,NKE,TSLA,UNH,XOM
Date,,,,,,,
2019-01-02,37.667183,147.848816,82.916214,68.839508,20.674667,221.528549,51.719875
2019-01-03,33.915257,144.590149,81.737839,67.621849,20.024000,215.487427,50.925774
2019-01-04,35.363071,148.886414,84.751144,69.387924,21.179333,218.007614,52.803398
2019-01-07,35.284363,151.819229,84.810051,70.382492,22.330667,218.426132,53.077988
2019-01-08,35.956985,152.548126,84.650131,71.321304,22.356667,221.346573,53.463894
...,...,...,...,...,...,...,...
2025-03-18,212.690002,349.570007,234.970001,73.309998,225.309998,503.799988,113.639999
2025-03-19,215.240005,353.420013,239.110001,72.989998,235.860001,503.200012,115.410004
2025-03-20,214.100006,355.519989,239.009995,71.860001,236.259995,511.299988,115.900002
2025-03-21,218.270004,351.149994,241.630005,67.940002,248.710007,516.849976,115.500000
2025-03-24,220.729996,363.769989,248.059998,67.389999,278.390015,516.500000,115.800003